apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: aci-helloworld 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aci-helloworld 
    spec:
      containers:
        - name: aci-helloworld 
          image: atulmakshelm.azurecr.io/aci-helloworld 
          ports:
          - containerPort: 3000